# Generated by Django 4.1.13 on 2026-05-26 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=40, unique=True)),
                ('remote_sync_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_configuration_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion de sincronizacion',
                'verbose_name_plural': 'Configuraciones de sincronizacion',
            },
        ),
    ]
