# Generated by Django 4.1.13 on 2026-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_syncconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconfiguration',
            name='remote_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='syncconfiguration',
            name='sync_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
