# Generated by Django 3.0.1 on 2023-10-17 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('Dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('Date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('Date_creation', models.DateTimeField(auto_now=True)),
                ('Date_update', models.DateTimeField(auto_now_add=True)),
                ('Age', models.PositiveIntegerField(default=0)),
                ('Salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('State', models.BooleanField(default=True)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%D')),
                ('CV', models.FileField(blank=True, null=True, upload_to='CV/%Y/%m/%D')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleado',
                'db_table': 'Empleado',
                'ordering': ['id'],
            },
        ),
    ]
