# Generated by Django 3.0.1 on 2023-10-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_client_detsale_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='Descripcion'),
        ),
    ]
