# Generated by Django 3.0.1 on 2023-11-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20231110_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='date_update',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user_update',
            new_name='user_updated',
        ),
    ]
