# Generated by Django 3.0.1 on 2023-11-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20231110_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
