# Generated by Django 3.0.1 on 2023-11-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20231110_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cate',
            new_name='cat',
        ),
    ]
