# Generated by Django 4.1.13 on 2026-04-23 01:09

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_organization_id_alter_user_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0015_alter_category_id_alter_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('sale', 'Venta'), ('income', 'Ingreso'), ('expense', 'Egreso'), ('opening', 'Apertura'), ('closing', 'Cierre'), ('refund', 'Reembolso')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cierre')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto apertura')),
                ('closing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto cierre')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto esperado')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferencia')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10, verbose_name='Estado')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255, verbose_name='Razón social')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre comercial')),
                ('rtn', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='El RTN debe contener 14 dígitos.', regex='^\\d{14}$')], verbose_name='RTN')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección fiscal')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^[0-9+\\-\\s]{8,20}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('cai', models.CharField(blank=True, max_length=50, null=True, verbose_name='CAI vigente')),
                ('cai_start_date', models.DateField(blank=True, null=True, verbose_name='Inicio CAI')),
                ('cai_end_date', models.DateField(blank=True, null=True, verbose_name='Fin CAI')),
                ('invoice_prefix', models.CharField(default='001-001-01-', max_length=20, verbose_name='Prefijo fiscal')),
                ('invoice_range_start', models.BigIntegerField(default=1, verbose_name='Rango inicial')),
                ('invoice_range_end', models.BigIntegerField(default=99999999, verbose_name='Rango final')),
                ('next_invoice_number', models.BigIntegerField(default=1, verbose_name='Siguiente número')),
                ('cash_sale_legend', models.CharField(blank=True, max_length=255, null=True, verbose_name='Leyenda de factura')),
            ],
            options={
                'verbose_name': 'Datos fiscales',
                'verbose_name_plural': 'Datos fiscales',
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('check', 'Cheque')], max_length=20, verbose_name='Método')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
            ],
            options={
                'verbose_name': 'Pago de compra',
                'verbose_name_plural': 'Pagos de compra',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('mobile', 'Pago móvil'), ('check', 'Cheque'), ('credit_note', 'Nota de crédito')], max_length=20, verbose_name='Método')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
            ],
            options={
                'verbose_name': 'Pago de venta',
                'verbose_name_plural': 'Pagos de venta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje')),
                ('code', models.CharField(default='EXENTO', max_length=20, verbose_name='Código')),
                ('is_default', models.BooleanField(default=False, verbose_name='Predeterminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tasa de impuesto',
                'verbose_name_plural': 'Tasas de impuesto',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='detpurchase',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de compra', 'verbose_name_plural': 'Detalles de compra'},
        ),
        migrations.AlterModelOptions(
            name='detsale',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de venta', 'verbose_name_plural': 'Detalles de venta'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-id'], 'verbose_name': 'Movimiento de inventario', 'verbose_name_plural': 'Movimientos de inventario'},
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='uniq_client_dni_per_org',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de crédito'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_credit_customer',
            field=models.BooleanField(default=False, verbose_name='Cliente a crédito'),
        ),
        migrations.AddField(
            model_name='client',
            name='rtn',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='El RTN debe contener 14 dígitos.', regex='^\\d{14}$')], verbose_name='RTN'),
        ),
        migrations.AddField(
            model_name='detpurchase',
            name='subtotal_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='detpurchase',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento línea'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='subtotal_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_decimal_qty',
            field=models.BooleanField(default=False, verbose_name='Permite fracción'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='erp.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código interno'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Es servicio'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('docena', 'Docena'), ('libra', 'Libra'), ('kilo', 'Kilo'), ('litro', 'Litro'), ('metro', 'Metro')], default='unidad', max_length=20, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vence'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de compra'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_term',
            field=models.CharField(choices=[('cash', 'Contado'), ('credit', 'Crédito')], default='cash', max_length=10, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada'), ('cancelled', 'Anulada')], default='draft', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_invoice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura proveedor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ISV'),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CAI'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('proforma', 'Proforma'), ('receipt', 'Recibo')], default='invoice', max_length=20, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vence'),
        ),
        migrations.AddField(
            model_name='sale',
            name='issue_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite CAI'),
        ),
        migrations.AddField(
            model_name='sale',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_term',
            field=models.CharField(choices=[('cash', 'Contado'), ('credit', 'Crédito'), ('mixed', 'Mixto')], default='cash', max_length=10, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada'), ('cancelled', 'Anulada')], default='draft', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ISV'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 1, 7, 22, 769298, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 1, 7, 43, 496398, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='La identidad hondureña debe contener 13 dígitos.', regex='^\\d{13}$')], verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], default='male', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^[0-9+\\-\\s]{8,20}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detpurchase',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='detpurchase',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='erp.product'),
        ),
        migrations.AlterField(
            model_name='detpurchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total línea'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio venta'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='erp.product'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total línea'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 1, 8, 4, 981144, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('adjustment_in', 'Ajuste Entrada'), ('adjustment_out', 'Ajuste Salida'), ('sale_cancel', 'Anulación venta'), ('purchase_cancel', 'Anulación compra'), ('return_sale', 'Devolución cliente'), ('return_purchase', 'Devolución proveedor')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_cat', to='erp.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 1, 8, 28, 124642, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 1, 8, 44, 997196, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='erp.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='erp.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 1, 9, 1, 354275, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 1, 9, 23, 483803, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^[0-9+\\-\\s]{8,20}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rtn',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='El RTN debe contener 14 dígitos.', regex='^\\d{14}$')], verbose_name='RTN'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'internal_code'], name='erp_product_organiz_e24c63_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'date_joined'], name='erp_purchas_organiz_459474_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'status'], name='erp_purchas_organiz_06bd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status'], name='erp_sale_organiz_d3b75a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'number'], name='erp_sale_organiz_810dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('dni__isnull', False)), fields=('organization', 'dni'), name='uniq_client_dni_per_org'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('rtn__isnull', False)), fields=('organization', 'rtn'), name='uniq_client_rtn_per_org'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('organization', 'barcode'), name='uniq_product_barcode_per_org'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_code__isnull', False)), fields=('organization', 'internal_code'), name='uniq_product_internal_code_per_org'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='user.organization'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='erp.cashsession'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='user.organization'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.sale'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='user.organization'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.purchase'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscaldata',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_data', to='user.organization'),
        ),
        migrations.AddField(
            model_name='fiscaldata',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscaldata',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='user.organization'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cash_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='erp.cashsession'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='user.organization'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detpurchase',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_details', to='erp.taxrate', verbose_name='ISV'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_details', to='erp.taxrate', verbose_name='ISV'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='erp.taxrate', verbose_name='ISV'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='erp.cashsession', verbose_name='Caja'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_tax_code_per_org'),
        ),
    ]
