# Generated by Django 4.1.13 on 2026-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_assign_uncategorized_products'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['organization', 'date_joined'], name='erp_invento_organiz_91ef35_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'date_joined'], name='erp_invento_product_711989_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference'], name='erp_invento_referen_766f2d_idx'),
        ),
    ]
