# Generated by Django 4.1.13 on 2026-04-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_organization_id_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organization/%Y/%m/%d', verbose_name='Logo'),
        ),
    ]
